# Generated by Django 4.2.2 on 2023-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
